### ISSUE TITLE
PF4J unable to recognize extensions, built using powertools

### ISSUE THREAD

**Issue by Mukarr** [gitblit-org/gitblit-powertools-plugin#2]
I am using PF4J framework, to build a modular application with plugins. I am using build.moxie and build.xml to auto-generate pom.xml for the plugins. I also used your plugin.java as a templete and defined extension as a separate public class.
When the jar is executed, the plugin is loaded successfully but PF4J does not recognize the extensions of the extension point defined.

**Comment by gitblit** [comment]
This does not sound like a problem with the powertools plugin for Gitblit.  This sounds like a question about using the PF4J framework.  Are you reporting your issue to the right project?

**Comment by Mukarr** [comment]
I do not know for sure, what is the root cause of the problem. Did you ever came across any such problem or know the probable cause of the one?

**Comment by gitblit** [comment]
I think you should follow-up on your PF4J issue with @decebals in his project. https://github.com/decebals/pf4j
